name: sistema_inventario
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  excel: ^4.0.6
  path_provider: ^2.1.5
  share_plus: ^12.0.1

  supabase_flutter: ^2.5.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - android/app/src/loginimg.png
    - assets/images/aguayo_fondo.png
    - assets/images/card_texture.png
    - assets/images/aguayo_rojo.png
    - assets/images/aguayo_azul.png
    - assets/images/aguayo_verde.png
    - assets/images/aguayo_morado.png
    - assets/images/aguayo_naranja.png
    - assets/images/aguayo_bg.png

